name: PaperTest
description: $description
version: '${version}'

main: dev.nitramnibus.papertest.PaperTest
paperPluginLoader: dev.nitramnibus.papertest.PaperTestLoader
api-version: '1.21.8'
load: POSTWORLD

authors: [ nitramnibus ]
